name: Build and push Docker image
on:
  create:
  workflow_dispatch:
    inputs:
      dispatchConfirmation:
        description: 'Please confirm the workflow dispatch'
        required: true
        default: 'Workflow dispatch confirmed'

jobs:
  build:
    if: ${{ github.event.ref_type == 'tag' || github.event.inputs.dispatchConfirmation == 'Workflow dispatch confirmed' }}
    name: Build and push Docker image
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Upgrade to at least corepack@0.31.0 to avoid
      # `Cannot find matching keyid` error
      # https://github.com/karlhorky/upleveled.io/pull/850#issuecomment-2646349719
      #
      # TODO: Remove when GitHub Actions runners have corepack@>=0.31.0
      - run: npm install -g corepack@>=0.31.0

      - run: corepack enable
      - run: echo 'PNPM_HOME="/home/runner/.local/share/pnpm"' >> $GITHUB_ENV
      - run: echo "$PNPM_HOME" >> $GITHUB_PATH

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - run: pnpm install

      # Publish to container registry
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
