name: size
on: [pull_request]
jobs:
  size:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
